apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mi-app-php
  name: mi-app-php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mi-app-php
  strategy: {}
  template:
    metadata:
      labels:
        app: mi-app-php
    spec:
      containers:
      - image: mi-app-php:v1
        name: mi-app-php
        resources: {}
status: {}
